# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.', null=True, upload_to='users/', verbose_name='Profile picture'),
        ),
    ]
