# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Order number of the image')),
                ('caption', models.TextField(help_text='Text to show at the bottom of the image.', verbose_name='Caption text for the image')),
                ('image', models.ImageField(help_text='Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.', upload_to='carousel/', verbose_name='Image file')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
