# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, help_text='Text to show at the bottom of the image. You may use MarkDown here.', null=True, verbose_name='Caption text for the image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.', upload_to='carousel', verbose_name='Image file'),
        ),
    ]
