# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title name for the course. Do not add any specific dates here.', max_length=200, verbose_name='Short title')),
                ('description', models.TextField(help_text='Complete description of the course. May contain special markup. Do not add any specific dates here.', verbose_name='Longer description')),
                ('image', models.ImageField(help_text='Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.', upload_to='courses/', verbose_name='General image of the course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='When this event is planned to happen', verbose_name='Date & time')),
                ('store_link', models.URLField(help_text='Provide complete URL to the web store.', verbose_name='Link to the web store')),
                ('course', models.ForeignKey(help_text='Course that this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.Course', verbose_name='Course')),
            ],
        ),
    ]
