# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tailored_page',
            field=models.CharField(blank=True, choices=[(b'base:landing_page', b'Landing page'), (b'courses:index', b'Courses')], help_text=b'Select the page that this item links to.', max_length=200, null=True),
        ),
    ]
